# Generated by Django 5.0.4 on 2024-05-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_order_product_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
